active_group: default
query_builder: true
default:
    dsn: ""
    hostname: localhost
    username: ""
    password: ""
    database: "../../storage/data/app.db"
    dbdriver: sqlite3
    dbprefix: ""
    pconnect: false
    db_debug: true
    cache_on: false
    cachedir: ""
    char_set: utf8
    dbcollat: utf8_general_ci
    swap_pre: ""
    encrypt: false
    compress: false
    stricton: false
    failover: []
    save_queries: true
