# Application
language: english
charset: UTF-8

# Logging
log:
    path: "../../storage/log/root/"
    dateFormat: "Y-m-d H:i:s"
    filePermissions: 0644
    fileExtension: ""
    threshold: 0

# Cache
cachePath: "../../storage/cache/root/"

# Session
sess:
    driver: files
    cookieName: mta_cms_root_session
    samesite: Lax
    expiration: 7200
    matchIp: false
    timeToUpdate: 300
    regenerateDestroy: false

# Cookie
cookie:
    prefix: ""
    domain: ""
    path: /
    secure: false
    httponly: false
    samesite: Lax

# Security
csrf:
    protection: false
    tokenName: csrf_test_name
    cookieName: csrf_cookie_name
    expire: 7200
    regenerate: true
    excludeUris: []

# Network
proxyIps: ""

# Routes
routes: []
